### ISSUE TITLE
Disaggregate

### ISSUE THREAD

**Issue by patrickocal** [cran/ioanalysis#1]
Hi Julian,

I have used this package in the near past and found it useful. Would you have some time in the next day or two to briefly discuss your “disaggregate” function. In particular:

1. What if, in order to produce the LQs, instead of output X, I have employment per sector for each region and for the “nation”. (My solution would be to assume constant marginal product of labour and simply scale down “national” output. Do you agree?)
2.	If I don’t have the colsum V of intermediate goods, then I would use the same principle as in 1. Do you agree?
3.	What if I don’t have the row sum U for intermediate goods? (This also relates to question 4.)
4.	I don’t understand how final demand is treated by disaggregate. Suppose:
> a.	I have two final demand columns at the national level (consumption and exports). 
> b.	I split these in proportion to employment as in 1 and 2. Would you agree with this step? Then, since I have regional Xs and regional fs, I would then be able to calculate regional row sums for intermediate production. 

Would steps (a) and (b) imply that the disaggregated column of final demand is unaffected by disaggregate?

5. I am having trouble understanding how you arrive at disaggregated final demand in the toy example in the manual. From the manual:
`X = list(toy.IO$X[1:5], toy.IO$X[6:10])`
`U = list(rowSums(toy.IO$Z[1:5, ]), rowSums(toy.IO$Z[6:10, ]))`
`V = list(colSums(toy.IO$Z[, 1:5]), colSums(toy.IO$Z[, 6:10]))`
`io = agg.region(toy.IO, regions = c(1,2), newname = "Magic")`
`A.new = disaggregate(io, X, U, V, new.regions = unique(toy.IO$RS_label[,1]))`
`Z.new = A.new %*% diag(c(unlist(X)))`
`io.new = as.inputoutput(Z = Z.new, X = unlist(X), RS_label = toy.IO$RS_label)`

I see that `isTRUE(toy.IO$f[1,1]+toy.IO$f[1,4]+toy.IO$f[6,1]+toy.IO$f[6,4]==io$f[1])` yields TRUE, which makes sense. So it is at the disaggregation stage that things "go wrong". In particular, I find that 
`toy.IO$f - io.new$f`
yields yields a vector of negative values. The absolute value of the differences is at least 200.

Your help is much appreciated.
Cheers,
Patrick

**Comment by patrickocal** [comment]
PS. Before I arrive at step 1 in the main question, I will need to aggregate some sectors and then disaggregate others. If I wish to use your disaggregate function to achieve this disaggregation, then should I create a pseudo region for the new sectors?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file. Thanks!

**Comment by patrickocal** [comment]
Okay, thanks!
